CREATE DATABASE IF NOT EXISTS feed CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE USER IF NOT EXISTS 'feed'@'%' IDENTIFIED BY 'feed';
GRANT ALL PRIVILEGES ON feed.* TO 'feed'@'%' IDENTIFIED BY 'feed';

FlUSH PRIVILEGES;
